
"use client";
import type { Dispatch, ReactNode, SetStateAction } from 'react';
import { createContext, useContext, useEffect, useState } from 'react';

export type Language = 'en' | 'ar';

interface LanguageContextType {
  language: Language;
  setLanguage: Dispatch<SetStateAction<Language>>;
  direction: 'ltr' | 'rtl';
  t: (key: string, defaultText: string, params?: Record<string, string | number>) => string; // Simple translation function
}

// Basic translations - extend as needed
const translations: Record<Language, Record<string, string>> = {
  en: {
    appName: "Asset Inspector Pro",
    selectCompany: "Select a Company",
    selectedCompany: "Selected Company",
    done: "Done",
    favorite: "Favorite",
    recent: "Recent",
    new: "New",
    createNewProject: "Create New Project",
    projectName: "Project Name",
    cancel: "Cancel",
    save: "Save",
    saving: "Saving...",
    newAsset: "New Asset",
    takePhotos: "Take Photos",
    uploadFromGallery: "Upload from Gallery",
    assetName: "Asset Name",
    description: "Description",
    speechToText: "Speech to Text",
    skip: "Skip",
    noProjectsFound: "No projects found in this category.",
    folders: "Folders",
    assets: "Assets",
    addNewFolder: "Add New Folder",
    addNewFolderToRoot: "Add New Folder to Root",
    folderName: "Folder Name",
    confirm: "Confirm",
    folderCreated: "Folder Created",
    allProjects: "All Projects",
    assetsIn: "Assets in",
    manageAssetsPrompt: "Manage assets within the selected folder or project root.",
    noAssetsInLocation: "No assets found in this location.",
    inside: "inside",
    to: "to",
    toProjectRoot: "to project root",
    folderNamePlaceholder: "e.g., Inspection Area 1",
    assetNameRequiredTitle: "Asset Name Required",
    assetNameRequiredDesc: "Please enter a name for the asset.",
    assetSavedTitle: "Asset Saved",
    assetSavedDesc: "Asset \"{assetName}\" has been saved.",
    nextAddPhotos: "Next: Add Photos",
    addDescriptionFor: "Add Description for:",
    provideDetailsPrompt: "Provide detailed information about the asset.",
    photosAdded: "Photos Added",
    editPhotos: "Add/Edit Photos",
    removePhotoTitle: "Remove photo",
    addPhotosFor: "Add Photos for",
    takeOrUploadPhotosPrompt: "You can take new photos or upload from your gallery. Max {MAX_PHOTOS} photos.",
    noPhotosAddedYet: "No photos added yet.",
    nextStepDescription: "Next: Description",
    skipPhotosAndNext: "Skip Photos & Next",
    savePhotosAndContinue: "Save Photos & Continue",
    backTo: "Back to",
    enterAssetNamePrompt: "Enter the asset name.",
    assetNamePlaceholder: "e.g., Main Entrance Column",
    inFolder: "In folder:",
    maxPhotosTitle: "Maximum {MAX_PHOTOS} Photos",
    maxPhotosDesc: "You can upload a maximum of {MAX_PHOTOS} photos.",
    maxPhotosReached: "You have reached the maximum of {MAX_PHOTOS} photos.",
    noCompaniesAvailable: "No companies available. Please check the data source.",
    useSpeech: "Use Speech",
    listening: "Listening...",
    aiSummary: "AI Summary",
    summarizing: "Summarizing...",
    aiGeneratedSummary: "AI Generated Summary:",
    saveDescription: "Save Description & Asset",
    typeOrUseSpeech: "Type or use voice to enter description...",
    cameraErrorTitle: "Camera Error",
    cameraErrorDesc: "Could not access the camera.",
    cameraAccessDeniedTitle: "Camera Access Denied",
    cameraAccessDeniedDesc: "Please enable camera permissions in your browser settings.",
    cameraNotFoundTitle: "Camera Not Found",
    cameraNotFoundDesc: "No camera was found. Please ensure a camera is connected and enabled.",
    photoCaptureErrorTitle: "Photo Capture Error",
    photoCaptureErrorDesc: "Could not capture photo.",
    startCamera: "Start Camera",
    startingCamera: "Starting...",
    capturePhoto: "Capture Photo",
    capturingPhoto: "Capturing...",
    stopCamera: "Stop Camera",
    projectNotFound: "Project Not Found",
    loadingProjectContext: "Loading project context...",
    step1Of3: "Step 1 of 3:",
    step2Of3: "Step 2 of 3:",
    step3Of3: "Step 3 of 3:",
    forProject: "for",
    unknownFolder: "Unknown Folder",
    previewPhotoAlt: "Preview {number}",
    projectContextLost: "Project context lost",
    noDescriptionAvailable: "No description available.",
    created: "Created",
    accessed: "Accessed",
    openProject: "Open Project",
    editProjectTitle: "Edit Project",
    editProjectDesc: "Update the details for your project.",
    projectDescription: "Project Description",
    projectDescriptionPlaceholder: "Enter a brief description of the project.",
    markAsFavorite: "Mark as Favorite",
    unmarkAsFavorite: "Unmark as Favorite",
    markedAsFavorite: "Marked as Favorite",
    unmarkedAsFavorite: "Unmarked as Favorite",
    updateProject: "Update Project",
    projectUpdatedTitle: "Project Updated",
    projectUpdatedDesc: "Project \"{projectName}\" has been successfully updated.",
    projectNamePlaceholder: "e.g., Spring Mall Inspection",
    editAssetTitle: "Edit Asset",
    assetNotFound: "Asset Not Found",
    assetUpdatedTitle: "Asset Updated",
    assetUpdatedDesc: "Asset \"{assetName}\" has been updated.",
    updateAssetButton: "Update Asset",
    editAssetDetailsTitle: "Edit Details for:",
    updateDetailsPrompt: "Update the details for this asset.",
    confirmPhotosAndContinue: "Confirm Photos & Continue",
    saveChangesAndContinue: "Save Changes & Continue",
    deleteAssetTitle: "Delete Asset",
    editFolderTitle: "Edit folder {folderName}",
    addRootFolderTitle: "Add folder to project root",
    addSubfolderTitle: "Add subfolder to {folderName}",
    projectRoot: "Project Root",
    noTopLevelFolders: "No top-level folders created yet.",
    folderNameRequiredTitle: "Folder Name Required",
    folderNameRequiredDesc: "Please enter a name for the folder.",
    folderUpdatedTitle: "Folder Updated",
    folderUpdatedDesc: "Folder \"{folderName}\" has been successfully updated.",
    editFolderModalTitle: "Edit Folder Name",
    editFolderDesc: "Update the name for your folder.",
    updateFolderButton: "Update Folder",
    editAssetPhotosTitle: "Edit Photos for",
    viewRootAssetsTitle: "View assets in project root",
    noFoldersInProject: "No folders in this project yet. Click \"Add New Folder\" to create one.",

  },
  ar: {
    appName: "مفتش الأصول برو",
    selectCompany: "اختر شركة",
    selectedCompany: "الشركة المختارة",
    done: "مكتمل",
    favorite: "مفضل",
    recent: "الأخيرة",
    new: "جديد",
    createNewProject: "إنشاء مشروع جديد",
    projectName: "اسم المشروع",
    cancel: "إلغاء",
    save: "حفظ",
    saving: "جاري الحفظ...",
    newAsset: "أصل جديد",
    takePhotos: "التقاط صور",
    uploadFromGallery: "تحميل من المعرض",
    assetName: "اسم الأصل",
    description: "الوصف",
    speechToText: "تحويل الكلام إلى نص",
    skip: "تخطي",
    noProjectsFound: "لا توجد مشاريع في هذه الفئة.",
    folders: "مجلدات",
    assets: "أصول",
    addNewFolder: "إضافة مجلد جديد",
    addNewFolderToRoot: "إضافة مجلد جديد إلى الجذر",
    folderName: "اسم المجلد",
    confirm: "تأكيد",
    folderCreated: "تم إنشاء المجلد",
    allProjects: "كل المشاريع",
    assetsIn: "الأصول في",
    manageAssetsPrompt: "إدارة الأصول داخل المجلد المحدد أو جذر المشروع.",
    noAssetsInLocation: "لا توجد أصول في هذا الموقع.",
    inside: "داخل",
    to: "إلى",
    toProjectRoot: "إلى جذر المشروع",
    folderNamePlaceholder: "مثال: منطقة الفحص 1",
    assetNameRequiredTitle: "اسم الأصل مطلوب",
    assetNameRequiredDesc: "الرجاء إدخال اسم للأصل.",
    assetSavedTitle: "تم حفظ الأصل",
    assetSavedDesc: "تم حفظ الأصل \"{assetName}\".",
    nextAddPhotos: "التالي: إضافة صور",
    addDescriptionFor: "إضافة وصف لـ:",
    provideDetailsPrompt: "قدم معلومات مفصلة عن الأصل.",
    photosAdded: "الصور المضافة",
    editPhotos: "إضافة/تعديل الصور",
    removePhotoTitle: "إزالة الصورة",
    addPhotosFor: "إضافة صور لـ",
    takeOrUploadPhotosPrompt: "يمكنك التقاط صور جديدة أو التحميل من معرض الصور الخاص بك. الحد الأقصى {MAX_PHOTOS} صور.",
    noPhotosAddedYet: "لم تتم إضافة أي صور بعد.",
    nextStepDescription: "التالي: الوصف",
    skipPhotosAndNext: "تخطي الصور والتالي",
    savePhotosAndContinue: "حفظ الصور والمتابعة",
    backTo: "العودة إلى",
    enterAssetNamePrompt: "أدخل اسم الأصل.",
    assetNamePlaceholder: "مثال: عمود المدخل الرئيسي",
    inFolder: "في المجلد:",
    maxPhotosTitle: "الحد الأقصى {MAX_PHOTOS} صور",
    maxPhotosDesc: "يمكنك تحميل {MAX_PHOTOS} صور كحد أقصى.",
    maxPhotosReached: "لقد وصلت إلى الحد الأقصى لعدد الصور وهو {MAX_PHOTOS} صور.",
    noCompaniesAvailable: "لا توجد شركات متاحة. يرجى التحقق من مصدر البيانات.",
    useSpeech: "استخدام الصوت",
    listening: "يستمع...",
    aiSummary: "ملخص الذكاء الاصطناعي",
    summarizing: "يلخص...",
    aiGeneratedSummary: "الملخص الذي تم إنشاؤه بواسطة الذكاء الاصطناعي:",
    saveDescription: "حفظ الوصف والأصل",
    typeOrUseSpeech: "اكتب أو استخدم الصوت لإدخال الوصف...",
    cameraErrorTitle: "خطأ في الكاميرا",
    cameraErrorDesc: "تعذر الوصول إلى الكاميرا.",
    cameraAccessDeniedTitle: "تم رفض الوصول إلى الكاميرا",
    cameraAccessDeniedDesc: "يرجى تمكين أذونات الكاميرا في إعدادات المتصفح.",
    cameraNotFoundTitle: "لم يتم العثور على كاميرا",
    cameraNotFoundDesc: "لم يتم العثور على كاميرا. يرجى التأكد من توصيل الكاميرا وتمكينها.",
    photoCaptureErrorTitle: "خطأ في التقاط الصورة",
    photoCaptureErrorDesc: "تعذر التقاط الصورة.",
    startCamera: "بدء الكاميرا",
    startingCamera: "جاري البدء...",
    capturePhoto: "التقاط صورة",
    capturingPhoto: "جاري الالتقاط...",
    stopCamera: "إيقاف الكاميرا",
    projectNotFound: "المشروع غير موجود",
    loadingProjectContext: "جاري تحميل سياق المشروع...",
    step1Of3: "الخطوة 1 من 3:",
    step2Of3: "الخطوة 2 من 3:",
    step3Of3: "الخطوة 3 من 3:",
    forProject: "لمشروع",
    unknownFolder: "مجلد غير معروف",
    previewPhotoAlt: "معاينة {number}",
    projectContextLost: "فقد سياق المشروع",
    noDescriptionAvailable: "لا يوجد وصف متاح.",
    created: "تم الإنشاء",
    accessed: "تم الوصول",
    openProject: "فتح المشروع",
    editProjectTitle: "تعديل المشروع",
    editProjectDesc: "قم بتحديث تفاصيل مشروعك.",
    projectDescription: "وصف المشروع",
    projectDescriptionPlaceholder: "أدخل وصفًا موجزًا للمشروع.",
    markAsFavorite: "وضع علامة كمفضل",
    unmarkAsFavorite: "إزالة العلامة كمفضل",
    markedAsFavorite: "تم وضع علامة كمفضل",
    unmarkedAsFavorite: "تمت إزالة العلامة كمفضل",
    updateProject: "تحديث المشروع",
    projectUpdatedTitle: "تم تحديث المشروع",
    projectUpdatedDesc: "تم تحديث المشروع \"{projectName}\" بنجاح.",
    projectNamePlaceholder: "مثال: فحص مول الربيع",
    editAssetTitle: "تعديل الأصل",
    assetNotFound: "الأصل غير موجود",
    assetUpdatedTitle: "تم تحديث الأصل",
    assetUpdatedDesc: "تم تحديث الأصل \"{assetName}\" بنجاح.",
    updateAssetButton: "تحديث الأصل",
    editAssetDetailsTitle: "تعديل تفاصيل لـ:",
    updateDetailsPrompt: "قم بتحديث تفاصيل هذا الأصل.",
    confirmPhotosAndContinue: "تأكيد الصور والمتابعة",
    saveChangesAndContinue: "حفظ التغييرات والمتابعة",
    deleteAssetTitle: "حذف الأصل",
    editFolderTitle: "تعديل المجلد {folderName}",
    addRootFolderTitle: "إضافة مجلد إلى جذر المشروع",
    addSubfolderTitle: "إضافة مجلد فرعي إلى {folderName}",
    projectRoot: "جذر المشروع",
    noTopLevelFolders: "لم يتم إنشاء مجلدات على المستوى الأعلى بعد.",
    folderNameRequiredTitle: "اسم المجلد مطلوب",
    folderNameRequiredDesc: "الرجاء إدخال اسم للمجلد.",
    folderUpdatedTitle: "تم تحديث المجلد",
    folderUpdatedDesc: "تم تحديث المجلد \"{folderName}\" بنجاح.",
    editFolderModalTitle: "تعديل اسم المجلد",
    editFolderDesc: "قم بتحديث اسم المجلد الخاص بك.",
    updateFolderButton: "تحديث المجلد",
    editAssetPhotosTitle: "تعديل صور لـ",
    viewRootAssetsTitle: "عرض الأصول في جذر المشروع",
    noFoldersInProject: "لا توجد مجلدات في هذا المشروع بعد. انقر فوق \"إضافة مجلد جديد\" لإنشاء واحد.",
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('en');
  const direction = language === 'ar' ? 'rtl' : 'ltr';

  useEffect(() => {
    document.documentElement.lang = language;
    document.documentElement.dir = direction;
  }, [language, direction]);

  const t = (key: string, defaultText: string, params?: Record<string, string | number>): string => {
    let text = translations[language]?.[key] || defaultText || key;
    if (params) {
      Object.keys(params).forEach(paramKey => {
        text = text.replace(`{${paramKey}}`, String(params[paramKey]));
      });
    }
    return text;
  };
  

  return (
    <LanguageContext.Provider value={{ language, setLanguage, direction, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}

