
"use client";
import type { Dispatch, ReactNode, SetStateAction } from 'react';
import { createContext, useContext, useEffect, useState } from 'react';

export type Language = 'en' | 'ar';

interface LanguageContextType {
  language: Language;
  setLanguage: Dispatch<SetStateAction<Language>>;
  direction: 'ltr' | 'rtl';
  t: (key: string, defaultText: string, params?: Record<string, string | number>) => string; // Simple translation function
}

// Basic translations - extend as needed
const translations: Record<Language, Record<string, string>> = {
  en: {
    appName: "Asset Inspector Pro",
    selectCompany: "Select a Company",
    selectCompanyDesc: "Choose a company profile to manage its inspection projects.",
    noCompaniesAvailable: "No companies available.",
    currentCompany: "Current Company",
    switchCompany: "Switch Company", 
    selectCompanyPrompt: "Select Company",
    done: "Done",
    favorite: "Favorite",
    recent: "Recent",
    new: "New",
    edit: "Edit",
    delete: "Delete",
    createNewProject: "Create New Project",
    createNewProjectDesc: "Enter a name for your new inspection project.",
    projectName: "Project Name",
    cancel: "Cancel",
    save: "Save",
    saving: "Saving...",
    loading: "Loading...", // Added loading key
    newAsset: "New Asset",
    takePhotos: "Take Photos", 
    uploadFromGallery: "Upload from Gallery",
    assetName: "Asset Name",
    description: "Description", 
    speechToText: "Speech to Text", // May be less relevant now with direct audio recording
    skip: "Skip",
    noProjectsFound: "No projects found in this category.", // Generic, can be overridden by more specific keys
    noProjectsFoundInTab: "No projects found in \"{tabName}\" tab.",
    folders: "Folders",
    assets: "Assets",
    addNewFolder: "Add New Folder",
    addNewFolderToRoot: "Add Folder to Root",
    addNewSubfolder: "Add New Subfolder",
    addNewSubfolderTo: "Add New Subfolder to \"{parentName}\"",
    folderName: "Folder Name",
    confirm: "Confirm",
    folderCreated: "Folder Created",
    folderCreatedNavigatedDesc: "Folder \"{folderName}\" created and selected.",
    projectCreatedTitle: "Project Created",
    projectCreatedDesc: "Project \"{projectName}\" has been successfully created.",
    allProjects: "All Projects",
    assetsIn: "Assets in",
    assetsInPath: "Path: ",
    manageAssetsPrompt: "Manage assets within the selected folder or project root.",
    noAssetsInLocation: "No assets found in this location.",
    inside: "inside",
    to: "to",
    toProjectRoot: "to project root",
    folderNamePlaceholder: "e.g., Inspection Area 1",
    assetNameRequiredTitle: "Asset Name Required",
    assetNameRequiredDesc: "Please enter a name for the asset.",
    assetSavedTitle: "Asset Saved",
    assetSavedDesc: "Asset \"{assetName}\" has been saved.",

    photosRequiredTitle: "Photos Required",
    photosRequiredDesc: "Please add at least one photo for the asset.",
    
    stepNameInputTitle: "Step 1: Asset Name", 
    stepPhotosCaptureTitle: "Step 2: Photos", 
    stepDescriptionsTitle: "Step 3: Descriptions",

    nextStepAddPhotos: "Next: Add Photos", 
    nextStepDescriptions: "Next: Add Descriptions", 
    
    addPhotosForAssetTitle: "Add Photos for:",
    addPhotosSectionTitle: "Add Photos",
    managePhotosButton: "Manage Photos",
    morePhotosInModal: "+{count} more. Click \"Manage Photos\" to see all.",

    addDetailsForAssetTitle: "Add Details for:",
    voiceDescriptionLabel: "Voice Description",
    recordVoiceDescriptionButton: "Record Voice", 
    playVoiceDescriptionButton: "Listen",
    pauseAudio: "Pause",
    finishRecording: "Finish Recording",
    voiceTranscriptPlaceholder: "Voice transcript will appear here...",
    textDescriptionLabel: "Written Description",
    textDescriptionPlaceholder: "Type detailed written description here...",
    
    backToPhotoCapture: "Back", 
    backToAssetNameModal: "Back", 
    saveAssetButton: "Finish", 

    descriptionRequiredForSaveTitle: "Description Required",
    descriptionRequiredForSaveDesc: "Please provide at least one form of description (voice or text).",
    unnamedAsset: "Unnamed Asset",
    managePhotosModalTitle: "Manage Photos for Asset:",
    managePhotosModalDesc: "Add more photos using your camera or gallery, or remove existing ones from the batch.",

    photosAdded: "Photos Added",
    editPhotos: "Add/Edit Photos",
    removePhotoTitle: "Remove photo",

    backTo: "Back to",
    backToProject: "Back to Project",
    enterAssetNamePrompt: "Enter the asset name.",
    assetNamePlaceholder: "e.g., Main Entrance Column",
    inFolder: "In folder:",
    forProject: "for",

    listening: "Listening...", // Still relevant for SpeechRecognition part

    cameraErrorTitle: "Camera Error",
    cameraErrorDesc: "Could not access the camera.",
    cameraAccessDeniedTitle: "Camera Access Denied",
    cameraAccessDeniedDesc: "Please enable camera permissions in your browser settings to use this app.",
    cameraAccessDeniedEnableSettings: 'Please enable camera permissions in your browser settings and refresh.',
    cameraNotFoundTitle: "Camera Not Found",
    cameraNotFoundDesc: "No camera was found. Please ensure a camera is connected and enabled.",
    photoCaptureErrorTitle: "Photo Capture Error",
    photoCaptureErrorDesc: "Could not capture photo.",
    canvasContextError: "Could not get canvas context.",
    cameraNotReadyError: "Camera not ready or permission denied.",
    projectNotFound: "Project Not Found",
    loadingProjectContext: "Loading project context...",
    folderNotFoundOrInvalid: "Folder not found or invalid for this project",


    previewPhotoAlt: "Preview {number}",
    previewBatchPhotoAlt: "Batch Preview {number}",
    noPhotosInBatch: "No photos in the current batch yet.",
    projectContextLost: "Project context lost",
    noDescriptionAvailable: "No description available.",
    voiceDescriptionOnly: "Voice description available", // This might change contextually if only audio is present
    textAndVoiceDescShort: "{text} (voice available)",
    created: "Created",
    accessed: "Accessed",
    editProjectTitle: "Edit Project",
    editProjectDesc: "Update the details for your project.",
    projectDescription: "Project Description",
    projectDescriptionPlaceholder: "Enter a brief description of the project.",
    markAsFavorite: "Mark as Favorite",
    unmarkAsFavorite: "Unmark as Favorite",
    markedAsFavorite: "Marked as Favorite",
    unmarkedAsFavorite: "Unmarked as Favorite",
    projectFavoriteStatusUpdatedDesc: "Project \"{projectName}\" favorite status updated.",
    updateProject: "Update Project",
    projectUpdatedTitle: "Project Updated",
    projectUpdatedDesc: "Project \"{projectName}\" has been successfully updated.",
    projectNameRequiredTitle: "Project Name Required",
    projectNameRequiredDesc: "Please enter a name for the project.",
    projectNamePlaceholder: "e.g., Spring Mall Inspection",
    editAssetTitle: "Edit Asset",
    assetNotFound: "Asset Not Found",
    assetUpdatedTitle: "Asset Updated",
    assetUpdatedDesc: "Asset \"{assetName}\" has been updated.",
    updateAssetButton: "Update Asset",
    editAssetDetailsTitle: "Edit Details for:",
    updateDetailsPrompt: "Update the details for this asset.",

    doneWithPhotos: 'Done with Photos',

    deleteAssetTitle: "Delete Asset",
    editFolderTitle: "Edit folder {folderName}",
    addRootFolderTitle: "New Folder", 
    addSubfolderTitle: "New subfolder to {folderName}",
    projectRoot: "Project Root",
    noTopLevelFolders: "No top-level folders created yet.",
    folderNameRequiredTitle: "Folder Name Required",
    folderNameRequiredDesc: "Please enter a name for the folder.",
    folderUpdatedTitle: "Folder Updated",
    folderUpdatedDesc: "Folder \"{folderName}\" has been successfully updated.",
    editFolderModalTitle: "Edit Folder Name",
    editFolderDesc: "Update the name for your folder.",
    editFolderDescContextual: "Update the name for folder: {folderName}",
    updateFolderButton: "Update Folder",

    viewRootAssetsTitle: "View assets in project root",
    noFoldersInProject: "This project has no folders yet.",
    noFoldersInProjectStart: "This project has no folders yet.",
    useFabToAddFolderMobile: "Use the \"Add New Folder\" button below to get started.",
    useFabToCreateContentMobile: "Use the buttons below to add a folder or asset.",
    createNewFolderInRootButton: "Create First Folder in Project Root",
    selectFolderForAssetTooltip: "Select or create a folder to add an asset",
    noFolderSelectedForAssetTitle: "Folder Required for Asset",
    noFolderSelectedForAssetDesc: "Please create or select a folder before adding an asset.",
    breadcrumbSeparator: ">",
    clickToNavigateTo: "Click to navigate to {name}",
    selectOrCreateFolderPrompt: "Select a folder below, or add a new folder to the project root.",
    manageFolderContentsPrompt: "Manage contents of \"{folderName}\", or add a subfolder.",
    contentsOfFolder: "Contents of \"{folderName}\"",
    projectRootContents: "Project Root - Folders & Assets",
    folderActions: "Folder actions",
    assetActions: "Asset actions",
    openFolder: "Open Folder",
    selectFolder: "Select Folder",
    editFolder: "Edit folder",
    deleteFolder: "Delete folder",
    deleteFolderConfirmation: "Are you sure you want to delete \"{folderName}\"? This action cannot be undone.",
    folderNotEmptyTitle: "Folder Not Empty",
    folderNotEmptyDesc: "Cannot delete folder. Please delete all subfolders and assets first.",
    folderDeletedTitle: "Folder Deleted",
    folderDeletedDesc: "Folder \"{folderName}\" has been deleted.",
    folderIsEmpty: "This folder is empty. Add a subfolder or asset.",
    projectRootIsEmpty: "This project is empty. Add a folder or asset to get started.",
    addSubfolderToCurrent: "Add subfolder here",
    expandFolder: "Expand folder",
    collapseFolder: "Collapse folder",
    viewAssetsInFolder: "View assets in {folderName}",

    takePhotosCustomCamera: "Take Photos (Camera)",
    initializingCamera: "Initializing Camera...",
    allowCameraAccessPrompt: "Please allow camera access when prompted.",
    capturePhoto: "Capture Photo",
    sessionPhotoPreviewAlt: "Session Preview {number}",
    doneWithSession: "Done", 
    doneWithSessionAddPhotos: "Add ({count})",
    currentPhotoBatch: "Current Photo Batch",
    customCameraViewTitle: "Custom Camera View",
    customCameraDialogTitle: "Camera",

    speechFeatureNotAvailableTitle: "Voice Recording Not Available", // Updated
    speechFeatureNotAvailableDesc: "Your browser may not support voice recording or microphone access is denied.", // Updated
    speechErrorNoSpeech: "No speech detected. Please try again.",
    speechErrorAudioCapture: "Audio capture failed. Check microphone permissions.",
    speechErrorNotAllowed: "Microphone access denied. Please allow microphone access.",
    speechErrorTitle: "Could not start speech recognition",
    speechStartErrorDesc: "Please ensure microphone permissions are granted.",
    speechSynthesisErrorTitle: "Speech Playback Error", // Less relevant now
    speechNoVoiceToPlayDesc: "Speech synthesis is not available or no voice description to play.", // Less relevant
    speechPlaybackNotAvailableTitle: "Speech Playback Not Available", // Less relevant
    speechPlaybackNotAvailableDesc: "Your browser does not support speech playback.", // Less relevant

    assetsInFolder: "Assets in \"{folderName}\"",
    assetsInProjectRoot: "Assets in Project Root",
    assetPhotoAlt: "Photo of {assetName}",
    editAssetButton: "Edit Asset",
    deleteAssetButton: "Delete Asset",
    deleteAssetConfirmationTitle: "Confirm Deletion",
    deleteAssetConfirmationDesc: "Are you sure you want to delete asset \"{assetName}\"?",
    assetDeletedTitle: "Asset Deleted",
    assetDeletedDesc: "Asset \"{assetName}\" has been deleted.",
    totalAssets: "{count} Assets",
    createdByInspectorShort: "Insp. Created",
    projectActionsMenuTitle: "Project Actions",
    deleteProjectButton: "Delete Project",
    deleteProjectConfirmationTitle: "Confirm Project Deletion",
    deleteProjectConfirmationDesc: "Are you sure you want to delete project \"{projectName}\"? This action cannot be undone and will delete all associated folders and assets.",
    projectDeletedTitle: "Project Deleted",
    projectDeletedDesc: "Project \"{projectName}\" has been deleted.",
    userNotAuthenticatedError: "User not authenticated. Cannot create project.",
    error: "Error",


    loginTitle: "Login",
    loginDesc: "Access your Asset Inspector Pro account.",
    emailLabel: "Email",
    passwordLabel: "Password",
    loginButton: "Login",
    noAccountPrompt: "Don't have an account?",
    signUpLink: "Sign up",
    signupTitle: "Create an Account",
    signupDesc: "Join Asset Inspector Pro today.",
    companyNameLabel: "Company Name",
    companyNamePlaceholder: "Your Company LLC",
    roleLabel: "Role",
    selectRolePlaceholder: "Select your role",
    adminRole: "Admin",
    inspectorRole: "Inspector",
    valuationRole: "Valuation",
    signupButton: "Sign Up",
    alreadyHaveAccountPrompt: "Already have an account?",
    loginLink: "Log in",
    logoutButton: "Logout",
    loadingUserSession: "Loading user session...",
    redirectingToLogin: "Redirecting to login...",
    projectsFor: "Projects for:",
    companyLabel: "Company:",
    loggedInAsRole: "Logged in as: {role}",
    
    adminDashboardTitle: "Admin Dashboard",
    adminDashboardDesc: "Overview of projects and team members for {companyName}.",
    adminDashboardMenuLink: "Admin Dashboard",
    companyProjectsTitle: "Company Projects",
    companyProjectsDescAdmin: "All projects associated with your company. Use the \"Assign Users\" button on each project card to manage assignments.",
    inspectorsTitle: "Inspectors",
    inspectorsDescAdmin: "List of all inspectors in your company and their assigned projects.",
    valuatorsTitle: "Valuators",
    valuatorsDescAdmin: "List of all valuators in your company and their assigned projects.",
    noInspectorsFound: "No inspectors found in this company.",
    noValuatorsFound: "No valuators found in this company.",
    loadingAdminData: "Loading dashboard data...",
    accessDeniedTitle: "Access Denied",
    accessDeniedAdminDesc: "You do not have permission to view this page.",
    genericError: "An error occurred.",
    signupFailedTitle: "Signup Failed",
    signupSuccessTitle: "Signup Successful",
    signupSuccessDesc: "You have been signed up and logged in.",
    actionNotImplemented: "Action Not Implemented",
    editProjectAdminPlaceholder: "Project editing from admin dashboard is a placeholder.",

    assignUsersButtonTitle: "Assign Users",
    assignUsersToProjectTitle: "Assign Users to:",
    assignUsersModalDescExtended: "Search for users by email to add them as Inspectors or Valuators to your company, then assign them to this project.",
    assignInspector: "Assign Inspector", 
    assignInspectorsLabel: "Assign Inspectors from Company", 
    assignValuator: "Assign Valuator", 
    assignValuatorsLabel: "Assign Valuators from Company", 
    selectInspectorPlaceholder: "Select an Inspector",
    selectValuatorPlaceholder: "Select a Valuator",
    unassign: "Unassign / None", 
    saveAssignmentsButton: "Save Assignments",
    assignmentsUpdatedTitle: "Assignments Updated",
    assignmentsUpdatedDesc: "Assignments for project \"{projectName}\" have been updated.",
    assignedProjectsListTitle: "Assigned Projects:",
    noProjectsAssigned: "No projects currently assigned.",
    noInspectorsFoundInCompany: "No inspectors currently in your company. Use search to add or assign roles.",
    noValuatorsFoundInCompany: "No valuators currently in your company. Use search to add or assign roles.",
    userNotFoundForInvite: "User with email \"{email}\" not found. They need an account to be assigned.",
    userRoleUpdatedTitle: "User Role Updated",
    userRoleUpdatedDesc: "User {email} is now a {role} in {companyName}.",
    makeInspectorButton: "Make Inspector",
    addAsInspectorButton: "Add as Inspector",
    makeValuatorButton: "Make Valuator",
    addAsValuatorButton: "Add as Valuator",
    userAlreadyRoleInCompany: "Already a {role} in this company.",
    noActionsAvailableForUser: "User found. No immediate role actions needed for this company.",
    searchUserByEmailLabel: "Search User by Email",
    emailPlaceholder: "user@example.com",
    searchResultsTitle: "Search Results",
    currentRoleLabel: "Role:",
    inYourCompanyShort: "(Your Company)",
    associatedWithCompanyLabel: "With:",
    noCompanyAffiliationLabel: "No current company affiliation",


    // New keys for modal flow
    stepPhotosCaptureTitleModal: "Step 1: Capture Photos",
    stepNameInputTitleModal: "Step 2: Asset Name",
    stepDescriptionsTitleModal: "Step 3: Descriptions & Save",
    provideNameForAsset: "Provide a name for your asset.",
    nextStepAssetName: "Next: Asset Name",
    cancelAssetCreation: "Cancel Asset Creation", 
    backToDashboard: "Back to Dashboard",


  },
  ar: {
    appName: "مفتش الأصول برو",
    selectCompany: "اختر شركة",
    selectCompanyDesc: "اختر ملف تعريف شركة لإدارة مشاريع الفحص الخاصة بها.",
    noCompaniesAvailable: "لا توجد شركات متاحة.",
    currentCompany: "الشركة الحالية",
    switchCompany: "تبديل الشركة",
    selectCompanyPrompt: "اختر شركة",
    done: "مكتمل",
    favorite: "مفضل",
    recent: "الأخيرة",
    new: "جديد",
    edit: "تعديل",
    delete: "حذف",
    createNewProject: "إنشاء مشروع جديد",
    createNewProjectDesc: "أدخل اسمًا لمشروع الفحص الجديد.",
    projectName: "اسم المشروع",
    cancel: "إلغاء",
    save: "حفظ",
    saving: "جاري الحفظ...",
    loading: "جاري التحميل...", // Added loading key
    newAsset: "أصل جديد",
    takePhotos: "التقاط صور",
    uploadFromGallery: "تحميل من المعرض",
    assetName: "اسم الأصل",
    description: "الوصف",
    speechToText: "تحويل الكلام إلى نص",
    skip: "تخطي",
    noProjectsFound: "لا توجد مشاريع في هذه الفئة.",
    noProjectsFoundInTab: "لا توجد مشاريع في علامة التبويب \"{tabName}\".",
    folders: "مجلدات",
    assets: "أصول",
    addNewFolder: "إضافة مجلد جديد",
    addNewFolderToRoot: "إضافة مجلد إلى الجذر",
    addNewSubfolder: "إضافة مجلد فرعي جديد",
    addNewSubfolderTo: "إضافة مجلد فرعي جديد إلى \"{parentName}\"",
    folderName: "اسم المجلد",
    confirm: "تأكيد",
    folderCreated: "تم إنشاء المجلد",
    folderCreatedNavigatedDesc: "تم إنشاء المجلد \"{folderName}\" واختياره.",
    projectCreatedTitle: "تم إنشاء المشروع",
    projectCreatedDesc: "تم إنشاء المشروع \"{projectName}\" بنجاح.",
    allProjects: "كل المشاريع",
    assetsIn: "الأصول في",
    assetsInPath: "المسار: ",
    manageAssetsPrompt: "إدارة الأصول داخل المجلد المحدد أو جذر المشروع.",
    noAssetsInLocation: "لا توجد أصول في هذا الموقع.",
    inside: "داخل",
    to: "إلى",
    toProjectRoot: "إلى جذر المشروع",
    folderNamePlaceholder: "مثال: منطقة الفحص 1",
    assetNameRequiredTitle: "اسم الأصل مطلوب",
    assetNameRequiredDesc: "الرجاء إدخال اسم للأصل.",
    assetSavedTitle: "تم حفظ الأصل",
    assetSavedDesc: "تم حفظ الأصل \"{assetName}\".",

    photosRequiredTitle: "الصور مطلوبة",
    photosRequiredDesc: "الرجاء إضافة صورة واحدة على الأقل للأصل.",
    
    stepNameInputTitle: "الخطوة ١: اسم الأصل", 
    stepPhotosCaptureTitle: "الخطوة ٢: الصور", 
    stepDescriptionsTitle: "الخطوة ٣: الأوصاف",

    nextStepAddPhotos: "التالي: إضافة الصور", 
    nextStepDescriptions: "التالي: إضافة الأوصاف", 
    
    addPhotosForAssetTitle: "إضافة صور لـ:",
    addPhotosSectionTitle: "إضافة صور",
    managePhotosButton: "إدارة الصور",
    morePhotosInModal: "+{count} أخرى. انقر فوق \"إدارة الصور\" لرؤية الكل.",

    addDetailsForAssetTitle: "إضافة تفاصيل لـ:",
    voiceDescriptionLabel: "الوصف الصوتي",
    recordVoiceDescriptionButton: "تسجيل صوتي", 
    playVoiceDescriptionButton: "استماع",
    pauseAudio: "إيقاف مؤقت",
    finishRecording: "إنهاء التسجيل",
    voiceTranscriptPlaceholder: "سيظهر النص الصوتي هنا...",
    textDescriptionLabel: "الوصف المكتوب",
    textDescriptionPlaceholder: "اكتب وصفًا مكتوبًا مفصلاً هنا...",
    
    backToPhotoCapture: "رجوع", 
    backToAssetNameModal: "رجوع", 
    saveAssetButton: "حفظ الأصل", 

    descriptionRequiredForSaveTitle: "الوصف مطلوب",
    descriptionRequiredForSaveDesc: "يرجى تقديم شكل واحد على الأقل من الوصف (صوتي أو نصي).",
    unnamedAsset: "أصل غير مسمى",
    managePhotosModalTitle: "إدارة صور الأصل:",
    managePhotosModalDesc: "أضف المزيد من الصور باستخدام الكاميرا أو المعرض، أو قم بإزالة الموجودة من الدفعة.",

    photosAdded: "الصور المضافة",
    editPhotos: "إضافة/تعديل الصور",
    removePhotoTitle: "إزالة الصورة",

    backTo: "العودة إلى",
    backToProject: "العودة إلى المشروع",
    enterAssetNamePrompt: "أدخل اسم الأصل.",
    assetNamePlaceholder: "مثال: عمود المدخل الرئيسي",
    inFolder: "في المجلد:",
    forProject: "لمشروع",

    listening: "يستمع...",

    cameraErrorTitle: "خطأ في الكاميرا",
    cameraErrorDesc: "تعذر الوصول إلى الكاميرا.",
    cameraAccessDeniedTitle: "تم رفض الوصول إلى الكاميرا",
    cameraAccessDeniedDesc: "يرجى تمكين أذونات الكاميرا في إعدادات المتصفح.",
    cameraAccessDeniedEnableSettings: 'يرجى تمكين أذونات الكاميرا في إعدادات المتصفح الخاصة بك وتحديث الصفحة.',
    cameraNotFoundTitle: "لم يتم العثور على كاميرا",
    cameraNotFoundDesc: "لم يتم العثور على كاميرا. يرجى التأكد من توصيل الكاميرا وتمكينها.",
    photoCaptureErrorTitle: "خطأ في التقاط الصورة",
    photoCaptureErrorDesc: "تعذر التقاط الصورة.",
    canvasContextError: "لم نتمكن من الحصول على سياق الرسم.",
    cameraNotReadyError: "الكاميرا ليست جاهزة أو تم رفض الإذن.",
    projectNotFound: "المشروع غير موجود",
    loadingProjectContext: "جاري تحميل سياق المشروع...",
    folderNotFoundOrInvalid: "المجلد غير موجود أو غير صالح لهذا المشروع",


    previewPhotoAlt: "معاينة {number}",
    previewBatchPhotoAlt: "معاينة الدفعة {number}",
    noPhotosInBatch: "لا توجد صور في الدفعة الحالية بعد.",
    projectContextLost: "فقد سياق المشروع",
    noDescriptionAvailable: "لا يوجد وصف متاح.",
    voiceDescriptionOnly: "الوصف الصوتي متوفر",
    textAndVoiceDescShort: "{text} (وصف صوتي متوفر)",
    created: "تم الإنشاء",
    accessed: "تم الوصول",
    editProjectTitle: "تعديل المشروع",
    editProjectDesc: "قم بتحديث تفاصيل مشروعك.",
    projectDescription: "وصف المشروع",
    projectDescriptionPlaceholder: "أدخل وصفًا موجزًا للمشروع.",
    markAsFavorite: "وضع علامة كمفضل",
    unmarkAsFavorite: "إزالة العلامة كمفضل",
    markedAsFavorite: "تم وضع علامة كمفضل",
    unmarkedAsFavorite: "تمت إزالة العلامة كمفضل",
    projectFavoriteStatusUpdatedDesc: "تم تحديث حالة المفضلة للمشروع \"{projectName}\".",
    updateProject: "تحديث المشروع",
    projectUpdatedTitle: "تم تحديث المشروع",
    projectUpdatedDesc: "تم تحديث المشروع \"{projectName}\" بنجاح.",
    projectNameRequiredTitle: "اسم المشروع مطلوب",
    projectNameRequiredDesc: "الرجاء إدخال اسم للمشروع.",
    projectNamePlaceholder: "مثال: فحص مول الربيع",
    editAssetTitle: "تعديل الأصل",
    assetNotFound: "الأصل غير موجود",
    assetUpdatedTitle: "تم تحديث الأصل",
    assetUpdatedDesc: "تم تحديث الأصل \"{assetName}\" بنجاح.",
    updateAssetButton: "تحديث الأصل",
    editAssetDetailsTitle: "تعديل تفاصيل لـ:",
    updateDetailsPrompt: "قم بتحديث تفاصيل هذا الأصل.",

    doneWithPhotos: 'تم الانتهاء من الصور',

    deleteAssetTitle: "حذف الأصل",
    editFolderTitle: "تعديل المجلد {folderName}",
    addRootFolderTitle: "مجلد جديد",
    addSubfolderTitle: "إضافة مجلد فرعي إلى {folderName}",
    projectRoot: "جذر المشروع",
    noTopLevelFolders: "لم يتم إنشاء مجلدات على المستوى الأعلى بعد.",
    folderNameRequiredTitle: "اسم المجلد مطلوب",
    folderNameRequiredDesc: "الرجاء إدخال اسم للمجلد.",
    folderUpdatedTitle: "تم تحديث المجلد",
    folderUpdatedDesc: "تم تحديث المجلد \"{folderName}\" بنجاح.",
    editFolderModalTitle: "تعديل اسم المجلد",
    editFolderDesc: "قم بتحديث اسم المجلد الخاص بك.",
    editFolderDescContextual: "تحديث اسم المجلد: {folderName}",
    updateFolderButton: "تحديث المجلد",

    viewRootAssetsTitle: "عرض الأصول في جذر المشروع",
    noFoldersInProject: "هذا المشروع لا يحتوي على مجلدات بعد.",
    noFoldersInProjectStart: "هذا المشروع لا يحتوي على مجلدات بعد.",
    useFabToAddFolderMobile: "استخدم زر \"إضافة مجلد جديد\" أدناه للبدء.",
    useFabToCreateContentMobile: "استخدم الأزرار أدناه لإضافة مجلد أو أصل.",
    createNewFolderInRootButton: "إنشاء أول مجلد في جذر المشروع",
    selectFolderForAssetTooltip: "حدد أو أنشئ مجلدًا لإضافة أصل إليه",
    noFolderSelectedForAssetTitle: "المجلد مطلوب للأصل",
    noFolderSelectedForAssetDesc: "يرجى إنشاء أو تحديد مجلد قبل إضافة أصل.",
    breadcrumbSeparator: "<",
    clickToNavigateTo: "انقر للانتقال إلى {name}",
    selectOrCreateFolderPrompt: "حدد مجلدًا أدناه، أو أضف مجلدًا جديدًا إلى جذر المشروع.",
    manageFolderContentsPrompt: "إدارة محتويات \"{folderName}\"، أو إضافة مجلد فرعي.",
    contentsOfFolder: "محتويات \"{folderName}\"",
    projectRootContents: "جذر المشروع - المجلدات والأصول",
    folderActions: "إجراءات المجلد",
    assetActions: "إجراءات الأصل",
    openFolder: "فتح المجلد",
    selectFolder: "تحديد المجلد",
    editFolder: "تعديل المجلد",
    deleteFolder: "حذف المجلد",
    deleteFolderConfirmation: "هل أنت متأكد أنك تريد حذف \"{folderName}\"؟ لا يمكن التراجع عن هذا الإجراء.",
    folderNotEmptyTitle: "المجلد ليس فارغًا",
    folderNotEmptyDesc: "لا يمكن حذف المجلد. يرجى حذف جميع المجلدات الفرعية والأصول أولاً.",
    folderDeletedTitle: "تم حذف المجلد",
    folderDeletedDesc: "تم حذف المجلد \"{folderName}\".",
    folderIsEmpty: "هذا المجلد فارغ. أضف مجلدًا فرعيًا أو أصلًا.",
    projectRootIsEmpty: "هذا المشروع فارغ. أضف مجلدًا أو أصلًا للبدء.",
    addSubfolderToCurrent: "إضافة مجلد فرعي هنا",
    expandFolder: "توسيع المجلد",
    collapseFolder: "طي المجلد",
    viewAssetsInFolder: "عرض الأصول في {folderName}",

    takePhotosCustomCamera: "التقاط صور (كاميرا)",
    initializingCamera: "جاري تهيئة الكاميرا...",
    allowCameraAccessPrompt: "يرجى السماح بالوصول إلى الكاميرا عند الطلب.",
    capturePhoto: "التقاط صورة",
    sessionPhotoPreviewAlt: "معاينة صورة الجلسة {number}",
    doneWithSession: "تم",
    doneWithSessionAddPhotos: "إضافة ({count})",
    currentPhotoBatch: "دفعة الصور الحالية",
    customCameraViewTitle: "عرض الكاميرا المخصص",
    customCameraDialogTitle: "الكاميرا",

    speechFeatureNotAvailableTitle: "تسجيل الصوت غير متوفر", // Updated
    speechFeatureNotAvailableDesc: "قد لا يدعم متصفحك تسجيل الصوت أو تم رفض الوصول إلى الميكروفون.", // Updated
    speechErrorNoSpeech: "لم يتم اكتشاف أي كلام. يرجى المحاولة مرة أخرى.",
    speechErrorAudioCapture: "فشل التقاط الصوت. تحقق من أذونات الميكروفون.",
    speechErrorNotAllowed: "تم رفض الوصول إلى الميكروفون. يرجى السماح بالوصول إلى الميكروفون.",
    speechErrorTitle: "تعذر بدء التعرف على الكلام",
    speechStartErrorDesc: "يرجى التأكد من منح أذونات الميكروفون.",
    speechSynthesisErrorTitle: "خطأ في تشغيل الكلام",
    speechNoVoiceToPlayDesc: "ميزة نطق النص غير متوفرة أو لا يوجد وصف صوتي لتشغيله.",
    speechPlaybackNotAvailableTitle: "تشغيل الكلام غير متوفر",
    speechPlaybackNotAvailableDesc: "متصفحك لا يدعم تشغيل الكلام.",


    assetsInFolder: "الأصول في \"{folderName}\"",
    assetsInProjectRoot: "الأصول في جذر المشروع",
    assetPhotoAlt: "صورة {assetName}",
    editAssetButton: "تعديل الأصل",
    deleteAssetButton: "حذف الأصل",
    deleteAssetConfirmationTitle: "تأكيد الحذف",
    deleteAssetConfirmationDesc: "هل أنت متأكد أنك تريد حذف الأصل \"{assetName}\"؟",
    assetDeletedTitle: "تم حذف الأصل",
    assetDeletedDesc: "تم حذف الأصل \"{assetName}\".",
    totalAssets: "{count} أصول",
    createdByInspectorShort: "إنشاء مفتش",
    projectActionsMenuTitle: "إجراءات المشروع",
    deleteProjectButton: "حذف المشروع",
    deleteProjectConfirmationTitle: "تأكيد حذف المشروع",
    deleteProjectConfirmationDesc: "هل أنت متأكد أنك تريد حذف المشروع \"{projectName}\"؟ لا يمكن التراجع عن هذا الإجراء وسيتم حذف جميع المجلدات والأصول المرتبطة به.",
    projectDeletedTitle: "تم حذف المشروع",
    projectDeletedDesc: "تم حذف المشروع \"{projectName}\".",
    userNotAuthenticatedError: "المستخدم غير مصادق عليه. لا يمكن إنشاء مشروع.",
    error: "خطأ",

    loginTitle: "تسجيل الدخول",
    loginDesc: "قم بالوصول إلى حساب Asset Inspector Pro الخاص بك.",
    emailLabel: "البريد الإلكتروني",
    passwordLabel: "كلمة المرور",
    loginButton: "تسجيل الدخول",
    noAccountPrompt: "ليس لديك حساب؟",
    signUpLink: "انشئ حساب",
    signupTitle: "إنشاء حساب",
    signupDesc: "انضم إلى Asset Inspector Pro اليوم.",
    companyNameLabel: "اسم الشركة",
    companyNamePlaceholder: "شركتك ذ.م.م",
    roleLabel: "الدور",
    selectRolePlaceholder: "اختر دورك",
    adminRole: "مسؤول",
    inspectorRole: "مفتش",
    valuationRole: "مقيم",
    signupButton: "انشاء حساب",
    alreadyHaveAccountPrompt: "هل لديك حساب بالفعل؟",
    loginLink: "تسجيل الدخول",
    logoutButton: "تسجيل الخروج",
    loadingUserSession: "جاري تحميل جلسة المستخدم...",
    redirectingToLogin: "إعادة التوجيه إلى صفحة تسجيل الدخول...",
    projectsFor: "مشاريع لـ:",
    companyLabel: "الشركة:",
    loggedInAsRole: "تم تسجيل الدخول كـ: {role}",
    
    adminDashboardTitle: "لوحة تحكم المسؤول",
    adminDashboardDesc: "نظرة عامة على المشاريع وأعضاء الفريق لـ {companyName}.",
    adminDashboardMenuLink: "لوحة تحكم المسؤول",
    companyProjectsTitle: "مشاريع الشركة",
    companyProjectsDescAdmin: "جميع المشاريع المرتبطة بشركتك. استخدم زر \"تعيين المستخدمين\" على كل بطاقة مشروع لإدارة التعيينات.",
    inspectorsTitle: "المفتشون",
    inspectorsDescAdmin: "قائمة بجميع المفتشين في شركتك ومشاريعهم المعينة.",
    valuatorsTitle: "المقيمون",
    valuatorsDescAdmin: "قائمة بجميع المقيمين في شركتك ومشاريعهم المعينة.",
    noInspectorsFound: "لم يتم العثور على مفتشين في هذه الشركة.",
    noValuatorsFound: "لم يتم العثور على مقيمين في هذه الشركة.",
    loadingAdminData: "جاري تحميل بيانات لوحة التحكم...",
    accessDeniedTitle: "تم رفض الوصول",
    accessDeniedAdminDesc: "ليس لديك إذن لعرض هذه الصفحة.",
    genericError: "حدث خطأ.",
    signupFailedTitle: "فشل التسجيل",
    signupSuccessTitle: "تم التسجيل بنجاح",
    signupSuccessDesc: "لقد تم تسجيلك وتسجيل دخولك.",
    actionNotImplemented: "الإجراء غير مُنفذ",
    editProjectAdminPlaceholder: "تعديل المشروع من لوحة تحكم المسؤول هو عنصر نائب.",

    assignUsersButtonTitle: "تعيين المستخدمين",
    assignUsersToProjectTitle: "تعيين مستخدمين للمشروع:",
    assignUsersModalDescExtended: "ابحث عن المستخدمين عن طريق البريد الإلكتروني لإضافتهم كمفتشين أو مقيمين لشركتك، ثم قم بتعيينهم لهذا المشروع.",
    assignInspector: "تعيين مفتش", 
    assignInspectorsLabel: "تعيين مفتشين من الشركة", 
    assignValuator: "تعيين مقيم", 
    assignValuatorsLabel: "تعيين مقيمين من الشركة", 
    selectInspectorPlaceholder: "اختر مفتشًا",
    selectValuatorPlaceholder: "اختر مقيمًا",
    unassign: "إلغاء التعيين / لا أحد",
    saveAssignmentsButton: "حفظ التعيينات",
    assignmentsUpdatedTitle: "تم تحديث التعيينات",
    assignmentsUpdatedDesc: "تم تحديث التعيينات للمشروع \"{projectName}\".",
    assignedProjectsListTitle: "المشاريع المعينة:",
    noProjectsAssigned: "لا توجد مشاريع معينة حاليًا.",
    noInspectorsFoundInCompany: "لا يوجد مفتشون حاليًا في شركتك. استخدم البحث لإضافة أو تعيين أدوار.",
    noValuatorsFoundInCompany: "لا يوجد مقيمون حاليًا في شركتك. استخدم البحث لإضافة أو تعيين أدوار.",
    userNotFoundForInvite: "المستخدم بالبريد الإلكتروني \"{email}\" غير موجود. يحتاجون إلى حساب ليتم تعيينهم.",
    userRoleUpdatedTitle: "تم تحديث دور المستخدم",
    userRoleUpdatedDesc: "المستخدم {email} هو الآن {role} في {companyName}.",
    makeInspectorButton: "جعله مفتشًا",
    addAsInspectorButton: "إضافة كمفتش",
    makeValuatorButton: "جعله مقيمًا",
    addAsValuatorButton: "إضافة كمقيم",
    userAlreadyRoleInCompany: "بالفعل {role} في هذه الشركة.",
    noActionsAvailableForUser: "تم العثور على المستخدم. لا توجد إجراءات دور فورية مطلوبة لهذه الشركة.",
    searchUserByEmailLabel: "البحث عن مستخدم بالبريد الإلكتروني",
    emailPlaceholder: "user@example.com",
    searchResultsTitle: "نتائج البحث",
    currentRoleLabel: "الدور:",
    inYourCompanyShort: "(شركتك)",
    associatedWithCompanyLabel: "مع:",
    noCompanyAffiliationLabel: "لا يوجد انتماء حالي لشركة",
    
    // New keys for modal flow
    stepPhotosCaptureTitleModal: "الخطوة 1: التقاط الصور",
    stepNameInputTitleModal: "الخطوة 2: اسم الأصل",
    stepDescriptionsTitleModal: "الخطوة 3: الأوصاف والحفظ",
    provideNameForAsset: "أدخل اسمًا للأصل الخاص بك.",
    nextStepAssetName: "التالي: اسم الأصل",
    cancelAssetCreation: "إلغاء إنشاء الأصل", 
    backToDashboard: "العودة إلى لوحة التحكم",

  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('en');
  const direction = language === 'ar' ? 'rtl' : 'ltr';

  useEffect(() => {
    document.documentElement.lang = language;
    document.documentElement.dir = direction;
  }, [language, direction]);

  const t = (key: string, defaultText: string, params?: Record<string, string | number>): string => {
    let text = translations[language]?.[key] || defaultText || key;
    if (params) {
      Object.keys(params).forEach(paramKey => {
        text = text.replace(`{${paramKey}}`, String(params[paramKey]));
      });
    }
    return text;
  };


  return (
    <LanguageContext.Provider value={{ language, setLanguage, direction, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}

